# Generated by Django 4.2.1 on 2023-09-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yapilypaymentid",
            name="user_uuid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
