# Generated by Django 4.2.1 on 2023-09-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_yapilypaymentid_user_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yapilypaymentid",
            old_name="user_uuid",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="yapilypaymentid",
            name="currency_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
