# Generated by Django 4.2.1 on 2023-05-25 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_rename_country_code_workflowai_currency_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowai",
            name="usd_rate",
        ),
    ]
