# Generated by Django 4.2.1 on 2023-09-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_yapilypaymentid_bank_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="yapilypaymentid",
            name="consent_token",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="yapilypaymentid",
            name="payment_idempotency_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="yapilypaymentid",
            name="payment_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
