# Generated by Django 4.2.1 on 2023-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_yapilypaymentid_consent_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yapilypaymentid",
            name="country_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="yapilypaymentid",
            name="data",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="yapilypaymentid",
            name="desc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="yapilypaymentid",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="yapilypaymentid",
            name="mail_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="yapilypaymentid",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="yapilypaymentid",
            name="payment_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="yapilypaymentid",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
