# Generated by Django 4.2.1 on 2023-09-18 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_yapilypaymentid_country_code_yapilypaymentid_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yapilypaymentid",
            old_name="data",
            new_name="date",
        ),
    ]
