# Generated by Django 4.2.1 on 2023-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0008_exchangerate"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=200)),
                ("amount", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=100)),
                ("order_id", models.CharField(max_length=100)),
            ],
        ),
    ]
