# Generated by Django 4.2.1 on 2023-07-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0009_transactiondetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiondetail",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
