# Generated by Django 4.2.1 on 2023-10-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0009_rename_status_yapilypaymentid_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yapilypaymentid",
            name="payment_status",
            field=models.CharField(
                blank=True, default="Initialized", max_length=10, null=True
            ),
        ),
    ]
