# Generated by Django 4.2.1 on 2023-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0011_alter_transactiondetail_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiondetail",
            name="session_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
