# Generated by Django 4.2.1 on 2023-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PPPCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=100)),
                ("currency_name", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=100)),
                ("currency_code", models.CharField(max_length=100)),
                ("world_bank_ppp", models.FloatField()),
                ("usd_exchange_rate", models.FloatField()),
            ],
        ),
    ]
