# Generated by Django 4.2.1 on 2023-10-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
