# Generated by Django 4.2.1 on 2023-10-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_transaction_payment_id_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="session_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
