# Generated by Django 4.2.1 on 2023-10-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="secondname",
            field=models.CharField(default="cris", max_length=100),
            preserve_default=False,
        ),
    ]
