# Generated by Django 4.2.1 on 2023-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0004_userprofile_firstname_userprofile_secondname"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
