# Generated by Django 4.2.1 on 2023-10-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="profile_images"
            ),
        ),
    ]
