# Generated by Django 4.2.1 on 2023-10-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0005_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
