# Generated by Django 4.2.1 on 2023-10-19 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0005_userprofile_phone_number_userprofile_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="secondname",
            new_name="lastname",
        ),
    ]
