# Generated by Django 4.2.1 on 2023-10-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_rename_secondname_userprofile_lastname"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="session_id",
            field=models.CharField(default="1", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="failed", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(max_length=255),
        ),
    ]
