# Generated by Django 4.2.1 on 2023-10-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_userprofile_reset_password_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="reset_password_token",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="avatar.jpg", null=True, upload_to="profile_images"
            ),
        ),
    ]
