# Generated by Django 4.2.1 on 2023-10-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0007_remove_userprofile_reset_password_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_images/avatar.jpg",
                null=True,
                upload_to="profile_images",
            ),
        ),
    ]
