# Generated by Django 4.2.1 on 2023-10-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0008_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
