# Generated by Django 4.2.1 on 2023-11-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0008_alter_userprofile_firstname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="id",
        ),
        migrations.AddField(
            model_name="wallet",
            name="wallet_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
