# Generated by Django 4.2.1 on 2023-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0009_remove_wallet_id_wallet_wallet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="wallet_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
