# Generated by Django 4.2.1 on 2023-11-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0010_alter_wallet_wallet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_id",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
