# Generated by Django 4.2.1 on 2023-11-04 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0011_wallet_id_alter_wallet_wallet_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="wallet_id",
            new_name="account_id",
        ),
    ]
