# Generated by Django 4.2.1 on 2023-11-04 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0012_rename_wallet_id_wallet_account_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="account_id",
            new_name="wallet_id",
        ),
    ]
