# Generated by Django 4.2.1 on 2023-11-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0014_rename_wallet_id_wallet_account_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="account_no",
            field=models.CharField(max_length=32),
        ),
    ]
