# Generated by Django 4.2.1 on 2023-11-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0016_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="account_no",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
