# Generated by Django 4.2.1 on 2023-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0017_alter_wallet_account_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="account_no",
            field=models.CharField(default="", max_length=32, null=True, unique=True),
        ),
    ]
