# Generated by Django 4.2.1 on 2023-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0018_alter_wallet_account_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="account_no",
            field=models.CharField(default="", max_length=20, null=True),
        ),
    ]
