# Generated by Django 4.2.1 on 2023-11-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0020_moneyrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="password",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
