# Generated by Django 4.2.1 on 2023-11-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0021_wallet_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
