# Generated by Django 4.2.1 on 2023-11-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0022_userprofile_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInitialazation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=10)),
                ("currency", models.CharField(max_length=10)),
                ("callback_url", models.CharField(max_length=100)),
                ("initialization_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address",
        ),
    ]
