# Generated by Django 4.2.1 on 2023-11-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0023_paymentinitialazation_remove_userprofile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinitialazation",
            name="price",
            field=models.IntegerField(),
        ),
    ]
