# Generated by Django 4.2.1 on 2023-11-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0024_alter_paymentinitialazation_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinitialazation",
            name="price",
            field=models.CharField(max_length=10),
        ),
    ]
