# Generated by Django 4.2.1 on 2023-11-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0026_transactions_userinfo_wallets"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wallets",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
