# Generated by Django 4.2.1 on 2023-11-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0027_userinfo_email_alter_wallets_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wallets",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
