# Generated by Django 4.2.1 on 2023-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0028_transactions_email_wallets_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="firstname",
            new_name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallets",
            name="account_no",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="wallets",
            name="password",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
