# Generated by Django 4.2.1 on 2023-11-28 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0030_userprofile_firstname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="totp_key",
        ),
    ]
