# Generated by Django 4.2.1 on 2023-11-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0031_remove_userprofile_totp_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallets",
            name="password",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
